#!/usr/bin/env bash
source "${THPM_THEME_ENV:-$HOME/.local/share/thpm/lib/theme-env.sh}"

if ! command -v zellij >/dev/null 2>&1; then
    skipped "Zellij"
fi

theme_dir="$HOME/.config/zellij/themes"
output_file="$theme_dir/current.kdl"
source_file="$HOME/.config/omarchy/current/theme/zellij.kdl"

mkdir -p "$theme_dir"

{
    printf '// Generated by thpm zellij plugin. Do not edit directly.\n'
    printf '// Set `theme "current"` in ~/.config/zellij/config.kdl to use this theme.\n\n'

    if [[ -f "$source_file" ]]; then
        cat "$source_file"
    else
        cat <<EOF
themes {
    current {
        text_unselected {
            base ${rgb_primary_foreground//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_yellow//,/}
            emphasis_1 ${rgb_normal_cyan//,/}
            emphasis_2 ${rgb_normal_green//,/}
            emphasis_3 ${rgb_normal_magenta//,/}
        }
        text_selected {
            base ${rgb_selection_foreground//,/}
            background ${rgb_selection_background//,/}
            emphasis_0 ${rgb_bright_yellow//,/}
            emphasis_1 ${rgb_bright_cyan//,/}
            emphasis_2 ${rgb_bright_green//,/}
            emphasis_3 ${rgb_bright_magenta//,/}
        }
        ribbon_selected {
            base ${rgb_primary_background//,/}
            background ${rgb_normal_blue//,/}
            emphasis_0 ${rgb_normal_red//,/}
            emphasis_1 ${rgb_normal_yellow//,/}
            emphasis_2 ${rgb_normal_magenta//,/}
            emphasis_3 ${rgb_normal_cyan//,/}
        }
        ribbon_unselected {
            base ${rgb_primary_foreground//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_bright_red//,/}
            emphasis_1 ${rgb_bright_yellow//,/}
            emphasis_2 ${rgb_bright_cyan//,/}
            emphasis_3 ${rgb_bright_magenta//,/}
        }
        table_title {
            base ${rgb_normal_blue//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_yellow//,/}
            emphasis_1 ${rgb_normal_cyan//,/}
            emphasis_2 ${rgb_normal_green//,/}
            emphasis_3 ${rgb_normal_magenta//,/}
        }
        table_cell_selected {
            base ${rgb_selection_foreground//,/}
            background ${rgb_selection_background//,/}
            emphasis_0 ${rgb_bright_yellow//,/}
            emphasis_1 ${rgb_bright_cyan//,/}
            emphasis_2 ${rgb_bright_green//,/}
            emphasis_3 ${rgb_bright_magenta//,/}
        }
        table_cell_unselected {
            base ${rgb_primary_foreground//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_yellow//,/}
            emphasis_1 ${rgb_normal_cyan//,/}
            emphasis_2 ${rgb_normal_green//,/}
            emphasis_3 ${rgb_normal_magenta//,/}
        }
        list_selected {
            base ${rgb_selection_foreground//,/}
            background ${rgb_selection_background//,/}
            emphasis_0 ${rgb_bright_yellow//,/}
            emphasis_1 ${rgb_bright_cyan//,/}
            emphasis_2 ${rgb_bright_green//,/}
            emphasis_3 ${rgb_bright_magenta//,/}
        }
        list_unselected {
            base ${rgb_primary_foreground//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_yellow//,/}
            emphasis_1 ${rgb_normal_cyan//,/}
            emphasis_2 ${rgb_normal_green//,/}
            emphasis_3 ${rgb_normal_magenta//,/}
        }
        frame_selected {
            base ${rgb_normal_blue//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_yellow//,/}
            emphasis_1 ${rgb_normal_cyan//,/}
            emphasis_2 ${rgb_normal_magenta//,/}
            emphasis_3 ${rgb_primary_background//,/}
        }
        frame_highlight {
            base ${rgb_normal_yellow//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_magenta//,/}
            emphasis_1 ${rgb_normal_yellow//,/}
            emphasis_2 ${rgb_bright_yellow//,/}
            emphasis_3 ${rgb_normal_red//,/}
        }
        exit_code_success {
            base ${rgb_normal_green//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_cyan//,/}
            emphasis_1 ${rgb_selection_background//,/}
            emphasis_2 ${rgb_normal_magenta//,/}
            emphasis_3 ${rgb_normal_blue//,/}
        }
        exit_code_error {
            base ${rgb_normal_red//,/}
            background ${rgb_primary_background//,/}
            emphasis_0 ${rgb_normal_yellow//,/}
            emphasis_1 ${rgb_primary_background//,/}
            emphasis_2 ${rgb_primary_background//,/}
            emphasis_3 ${rgb_primary_background//,/}
        }
        multiplayer_user_colors {
            player_1 ${rgb_normal_magenta//,/}
            player_2 ${rgb_normal_blue//,/}
            player_3 ${rgb_normal_cyan//,/}
            player_4 ${rgb_normal_yellow//,/}
            player_5 ${rgb_bright_magenta//,/}
            player_6 ${rgb_bright_blue//,/}
            player_7 ${rgb_bright_cyan//,/}
            player_8 ${rgb_bright_yellow//,/}
            player_9 ${rgb_normal_green//,/}
            player_10 ${rgb_normal_red//,/}
        }
    }
}
EOF
    fi
} > "$output_file"

success "Zellij theme updated!"
